---
- name: Ensure Dockerconfig directory exists
  ansible.builtin.file:
    path: "{{ docker_host_stacks_dir }}"
    state: directory
    mode: "2775"
    group: "homelab-devs"
    owner: "{{ my_user }}"
