deploy_user: "{{ vault_deploy_user }}"
my_user: "{{ vault_my_user }}"
deploy_user_key: "{{ vault_deploy_key }}"
ansible_become_password: "{{ vault_ansible_become_password }}"
deploy_user_pass: "{{ vault_deploy_user_pass }}"
deploy_ssh_key: "{{ vault_deploy_ssh_key }}"
sops_key: "{{ vault_sops_key }}"
cloudflare_token: "{{ vault_cloudflare_token }}"
cloudflare_domain: "{{ vault_cloudflare_domain }}"
nut_server_admin_pass: "{{ vault_nut_server_admin_pass }}"
nut_server_admin_user: "{{ vault_nut_server_admin_user }}"
email_to: "{{ vault_email_to }}"
ha_token: "{{ vault_ha_token }}"
cadvisor_endpoint: "{{ vault_cadvisor_endpoint }}"
pve_host_endpoint: "{{ vault_pve_host_endpoint }}"
pve_exporter_name: "{{ vault_pve_exporter_name }}"
pve_exporter_token_name: "{{ vault_pve_exporter_token_name }}"
pve_exporter_token: "{{ vault_pve_exporter_token }}"
