---
- name: Restart NUT server service
  ansible.builtin.service:
    name: nut-server
    state: restarted
  listen: restart nut-server

- name: Restart NUT client service
  ansible.builtin.service:
    name: nut-client
    state: restarted
  listen: restart nut-client
