---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest@sha256:35c66180741213ad9d8a4a31271fa7e84f290b681ece3fb84359c1ca7013da89
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - PASSWORD=${PASSWORD}
      - PROXY_DOMAIN=${DOMAIN}
      - DEFAULT_WORKSPACE=/config/workspace
      - SUDO_PASSWORD=${SUDO_PASSWORD}
    volumes:
      - /dockerconfig/codeserver/config:/config
      - /dockerconfig:/dockerconfig
      - /hdd:/hdd
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
