---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest@sha256:54bcdbe29ee46428409b9334cc5328c591ba42ae81bfe146f6658084f2cf1809
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - PASSWORD=${PASSWORD}
      - PROXY_DOMAIN=${DOMAIN}
      - DEFAULT_WORKSPACE=/config/workspace
      - SUDO_PASSWORD=${SUDO_PASSWORD}
    volumes:
      - /dockerconfig/codeserver/config:/config
      - /dockerconfig:/dockerconfig
      - /hdd:/hdd
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
