name: "Docker"
description: "This VM runs most of the (not categorised) **production** Docker containers"
environment: "Production"
type: "VM"
status: "Active"
os: "Ubuntu"
ports:
  - name: "Nginx Proxy Manager WebUI"
    port: 81
    protocol: "tcp"
    access: "Internal"
  - name: "Nginx Proxy Manager SSL"
    port: 443
    protocol: "tcp"
    access: "Internal/External"
  - name: "Nginx Proxy Manager HTTP"
    port: 80
    protocol: "tcp"
    access: "Internal/External"
  - name: "QBittorrent Incoming Connections"
    port: 51000
    protocol: "tcp/udp"
    access: "Internal/External"
    
docker:
  - "Audiobookshelf"
  - "Codeserver"
  - "Firefly3"
  - "Homepage"
  - "Jackett"
  - "Mealie"
  - "Nginx"
  - "Peanut"
  - "Portainer"
  - "Qbittorrent"
  - "Searxng"
  - "Thememusicdownloader"
  - "Watchtower"
  - "Bitwarden"
  - "Esphome"
  - "Glances"
  - "It-Tools"
  - "Littlelink"
  - "Navidrome"
  - "Ombi"
  - "Photoprism"
  - "Prowlarr"
  - "Radarr"
  - "Sonarr"
  - "[Watcher-Agent](https://ghcr.io/l1p0-m/config-watcher-agent)"