app_stacks:
  - "../PVE/Docker/Configs/radarr"
  - "../PVE/Docker/Configs/audiobookshelf"
  - "../PVE/Docker/Configs/codeserver"
  - "../PVE/Docker/Configs/firefly3"
  - "../PVE/Docker/Configs/homepage"
  - "../PVE/Docker/Configs/jackett"
  - "../PVE/Docker/Configs/mealie"
  - "../PVE/Docker/Configs/nginx"
  - "../PVE/Docker/Configs/peanut"
  - "../PVE/Docker/Configs/portainer"
  - "../PVE/Docker/Configs/qbittorrent"
  - "../PVE/Docker/Configs/searxng"
  - "../PVE/Docker/Configs/thememusicdownloader"
  - "../PVE/Docker/Configs/watchtower"
  - "../PVE/Docker/Configs/bitwarden"
  - "../PVE/Docker/Configs/esphome"
  - "../PVE/Docker/Configs/glances"
  - "../PVE/Docker/Configs/it-tools"
  - "../PVE/Docker/Configs/littlelink"
  - "../PVE/Docker/Configs/navidrome"
  - "../PVE/Docker/Configs/ombi"
  - "../PVE/Docker/Configs/photoprism"
  - "../PVE/Docker/Configs/prowlarr"
  - "../PVE/Docker/Configs/radarr"
  - "../PVE/Docker/Configs/sonarr"
  - "../PVE/Docker/Configs/watcher_agent"
  - "../PVE/Docker/Configs/youtube-dl"
