app_stacks:
  - "../PVE/Docs_Monitoring/Configs/docker_socket_proxy"
  - "../PVE/Docs_Monitoring/Configs/gitea"
  - "../PVE/Docs_Monitoring/Configs/grafana"
  - "../PVE/Docs_Monitoring/Configs/portainer_agent"
  - "../PVE/Docs_Monitoring/Configs/speedtest"
  - "../PVE/Docs_Monitoring/Configs/watcher_agent"

app_templates:
  - "../PVE/Docs_Monitoring/Configs/grafana/config/prometheus/prometheus.yml.template.j2"
  - "../PVE/Docs_Monitoring/Configs/grafana/config/pve-exporter/pve.yml.template.j2"
