---

ups_nut_mode: netserver
ups_nut_ups_name: "zinto800"
ups_nut_ups_desc: "UPS for the whole Rack"
ups_nut_ups_driver: "blazer_usb"
ups_nut_ups_port: "auto"
ups_nut_ups_vendorid: "0665"
ups_nut_ups_productid: "5161"
ups_nut_ups_bus: "005"
ups_nut_ups_battery_voltage_high: 27.30
ups_nut_ups_battery_voltage_low: 22.00
ups_nut_ups_runtimecal: 360,100,840,50
ups_nut_listen_ip: "0.0.0.0"
ups_nut_listen_port: "3493"
ups_nut_admin_user: "{{ nut_server_admin_user }}"
ups_nut_admin_password: "{{ nut_server_admin_pass }}"
