---

printer_print_packages:
  - cups
  - cups-filters
  - cups-client
  - sane
  - sane-backends
  - sane-saned

printer_print_groups:
  - lp
  - scanner

printer_cups_service_name: "cupsd"
printer_sane_service_name: "saned"
