---

printer_print_packages:
  - cups
  - cups-filters
  - cups-client
  - sane
  - sane-utils
  - saned

printer_print_groups:
  - lp
  - lpadmin
  - scanner
  - saned

printer_cups_service_name: "cups"
printer_sane_service_name: "saned"
