---
vpn_wg_address: "10.22.120.1/24"
vpn_wg_network_address: "10.22.120.0/24"
vpn_wg_dns: "8.8.8.8"
vpn_wg_interface: "wg0"
vpn_wg_network_iface: "eth0"
vpn_wg_port: "51820"
vpn_wg_allowed_ips: "10.22.120.0/24, 192.168.1.0/24"
