import os
from pathlib import Path as pathlibpath
import hcl2
from argparse import ArgumentParser
import hashlib
from shutil import move as movefile


def read_tfvars_file(tfvars_path):
    if os.path.exists(tfvars_path):
        try:
            with open(tfvars_path, "r") as tfvars_file:
                return clean_values(hcl2.load(tfvars_file))
            
        except Exception as e:
            print(f"Error reading tfvars file: {e}")
            return False
    return False

def clean_values(val):
    if isinstance(val, int):
        return val
    elif isinstance(val, str):
        return val.strip().strip('"').strip("'").strip()
    elif isinstance(val, list):
        return [clean_values(item) for item in val]
    elif isinstance(val, dict):
        return {k: clean_values(v) for k, v in val.items()}

def find_tfvars_file(search_path="/"):
    all_tfvars_values = {}
    for files in sorted(pathlibpath(search_path).rglob("terraform.tfvars")):
        print(f"Found terraform.tfvars file at: {files}")
        tfvars_values = read_tfvars_file(files)
        if tfvars_values:
            all_tfvars_values[files] = tfvars_values
    if all_tfvars_values:
        return all_tfvars_values
    return False

def get_ssh_config_from_env():
    ssh_config = {
        "ssh_user": os.getenv("SSH_USER", "deploy"),
        "ssh_port": os.getenv("SSH_PORT", "22"),
    }
    return ssh_config

def process_tfvars_values(all_vars):
    clean_vars = {}
    for file_path, tfvars in all_vars.items():
        print(f"Processing tfvars from: {file_path}")
        tfvars_config = tfvars.get("config", {})

        if tfvars_config:
            ip_address_raw = tfvars_config.get("ip_address", "N/A")
            ip_address = ip_address_raw.split("/")[0] if "/" in str(ip_address_raw) else ip_address_raw
            target_type = tfvars.get("target_type", "N/A").upper()
            name = tfvars_config.get("name", "N/A") if target_type == "LXC" else tfvars_config.get("vm_name", "N/A")
            print(f"Name: {name}, IP Address: {ip_address}, Target Type: {target_type}")
            default_groups = [f"{target_type.lower()}"]
            groups = tfvars.get("ansible_groups", default_groups)
            ssh_config = get_ssh_config_from_env()
            ssh_user = ssh_config.get("ssh_user", "deploy")

            original_name = name
            counter = 1
            while name in clean_vars:
                print(f"Warning: Duplicate entry for '{name}' found. Renaming it...")
                name = f"{original_name}_{counter}"
                counter += 1

            clean_vars[name] = {"name": name, "ip_address": ip_address, "target_type": target_type, "groups": groups, "ssh_user": ssh_user}

    if clean_vars:
        return clean_vars
    return False

def generate_ansible_inventory(vars):
    lines = [
        "# ===================================================#",
        "# AUTOMATICALLY GENERATED BY CI/CD                   #",
        "# DO NOT EDIT MANUALLY - CHANGES WILL BE OVERWRITTEN #",
        "# ===================================================#\n",
        "[all:children]",
        "proxmox_lxcs",
        "proxmox_vms",
    ]
    if vars:
        lxcs = []
        vms = []
        custom_groups = {}
        for name, details in vars.items():
            entry = f"{name} ansible_host={details['ip_address']} ansible_user={details['ssh_user']}" 
            print(f"Adding {name} to inventory with IP {details['ip_address']} and type {details['target_type']}")
            if details.get("target_type") == "LXC":
                lxcs.append(entry)

            if details.get("target_type") == "VM":
                vms.append(entry)

            if details.get("groups"):
                for group in details["groups"]:
                    if group not in ["proxmox_vms", "proxmox_lxcs", "all", "vm", "lxc", "lxcs", "vms"]:
                        if group not in custom_groups:
                            custom_groups[group] = []
                        custom_groups[group].append(entry)

        lines.append("\n[proxmox_vms]")
        lines.extend(sorted(vms))

        lines.append("\n[proxmox_lxcs]")
        lines.extend(sorted(lxcs))

        if custom_groups:
            for group_name, group_entries in custom_groups.items():
                lines.append(f"\n[{group_name}]")
                lines.extend(sorted(group_entries))

        lines.append("")
        content = "\n".join(lines)

        print("Generating Ansible inventory file...")
        print(content)
        return content

def check_if_file_changed(file_path, new_file):
    if os.path.exists(file_path):
        with open(file_path, "rb") as existing_file:
            exiting_digest = hashlib.file_digest(existing_file, "sha256")
        with open(new_file, "rb") as new_file:
            new_digest = hashlib.file_digest(new_file, "sha256")
        return exiting_digest.hexdigest() != new_digest.hexdigest()
    return True

def write_inventory_to_file(inventory_content):
    try:
        output_path = pathlibpath("./inventory.ini.new")

        with open(output_path, "w") as inventory_file:
            inventory_file.write(inventory_content)
        print(f"Ansible inventory successfully written to {output_path}")
        return True
    except Exception as e:
        print(f"Error writing Ansible inventory to file: {e}")
        return False

def write_to_github_output(has_changes, pr_title, pr_branch, pr_body):
    github_output = os.getenv('GITHUB_OUTPUT')
    if github_output:
        with open(github_output, 'a') as f:
            f.write(f"has_changes={has_changes}\n")
            f.write(f"pr_title={pr_title}\n")
            f.write(f"pr_branch={pr_branch}\n")
            f.write("pr_body<<EOF\n")
            f.write(f"{pr_body}\n")
            f.write("EOF\n")

if __name__ == "__main__":
    arg_parser = ArgumentParser(description="Generate Ansible inventory from Terraform tfvars files.")
    arg_parser.add_argument("--output", type=str, default="/ansible/inventory.ini", help="Output path for the generated Ansible inventory file.")
    arg_parser.add_argument("--search", type=str, default="/", help="Search path for Terraform tfvars files.")
    args = arg_parser.parse_args()
    arg_output_path = args.output
    arg_search_path = args.search

    try:
        all_vars = find_tfvars_file(search_path=arg_search_path)
        if all_vars:
            clean_vars = process_tfvars_values(all_vars)

            if clean_vars:
                inventory_content = generate_ansible_inventory(clean_vars)
                write_inventory_to_file(inventory_content)

                if check_if_file_changed(pathlibpath(arg_output_path), pathlibpath("inventory.ini.new")):
                    if not os.path.exists(pathlibpath(arg_output_path).parent):
                        os.makedirs(pathlibpath(arg_output_path).parent, exist_ok=True)
                    movefile(src="inventory.ini.new", dst=arg_output_path)
                    print(f"Ansible inventory updated at: {arg_output_path}")
                    has_changes = True

                else:
                    print("No changes detected in the Ansible inventory. No update performed.")
                    has_changes = False
                write_to_github_output(has_changes=has_changes, pr_title="Update Ansible Inventory", pr_branch="update-ansible-inventory", pr_body="Ansible inventory has been updated based on the latest Terraform tfvars files.")

    except Exception as e:
        print(f"An error occurred: {e}")
