---
services:
  drift-watcher:
    image: ghcr.io/l1p0-m/config-watcher-agent:v1.1.0
    container_name: watcher-agent
    restart: unless-stopped
    environment:
      - REPO=L1p0-M/Homelab
      - NODE=PVE
      - VM_NAME=Docker
      - CONFIGDIR=/app/dockerconfig
      - CRON_SCHEDULE=0 23 * * mon   # Run every Monday at 23:00
      - DRY_RUN=false
      - PUID=1000
      - PGID=1000
      - EMAIL_TO=${EMAIL_TO}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_FROM_NAME=Watcher
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    volumes:
      - /dockerconfig:/app/dockerconfig
      - /dockerconfig/watcher_agent/trash:/app/trash
