---
services:
  runner-controller:
    image: ghcr.io/l1p0-m/github-runner-controller:v2.337.0
    container_name: runner-controller
    restart: unless-stopped
    environment:
      - PUID=1000
      - DEBUG=info
      - PGID=1000
      - TZ=Europe/Budapest
      - TOKEN=${TOKEN}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dockerconfig/github_runner/config.toml:/app/config.toml
