services:
    renovate:
        image: ghcr.io/l1p0-m/renovate-cron:44.41
        container_name: renovate_bot
        restart: always
        volumes:
            - /dockerconfig/renovate_bot/config.js:/usr/src/app/config.js
            - /dockerconfig/renovate_bot/tmp:/tmp/renovate
        environment:
            - RENOVATE_BASE_DIR=/tmp/renovate
            - RENOVATE_TOKEN=${TOKEN}
            - RENOVATE_PLATFORM=github
            - RENOVATE_GIT_AUTHOR=${AUTHOR}
            - RENOVATE_SCHEDULE_INTERVAL=1h
            - RENOVATE_IGNORE_PR_AUTHOR=true
      #     - RENOVATE_AUTODISCOVER=true
            - CRON_SCHEDULE=0 * * * *
            - PGID=1000
            - PUID=1000
            - RENOVATE_REPOSITORY_CACHE=enabled
            - RENOVATE_REPOSITORIES=L1p0-M/Homelab
