services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest@sha256:c19aa4ecdf03d73e1d5c901da33744cb7eb4d921f89bafed1ca264601d7fa224
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/sonarr/config:/config
      - /hddpool3:/hdd1
      - /hddpool4:/hdd3
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
