services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest@sha256:4d9df314875e1249ab7d6170c2b9b3dc1d8e6383f168ceb10dc9a5ad9b324739
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/sonarr/config:/config
      - /hddpool3:/hdd1
      - /hddpool4:/hdd3
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
