---
- name: Generate client private keys
  ansible.builtin.shell:
    cmd: "set -o pipefail && wg genkey | tee /etc/wireguard/keys/{{ item.name }}_priv | wg pubkey > /etc/wireguard/keys/{{ item.name }}_pub"
    creates: "/etc/wireguard/keys/{{ item.name }}_priv"
    executable: "/bin/bash"
  loop: "{{ vpn_wg_clients }}"
  no_log: true

- name: Read client public keys
  ansible.builtin.slurp:
    src: "/etc/wireguard/keys/{{ item.name }}_pub"
  register: vpn_wg_client_public_keys_raw
  changed_when: false
  loop: "{{ vpn_wg_clients }}"
  no_log: true

- name: Map client public keys to dictionary
  ansible.builtin.set_fact:
    vpn_wg_client_public_keys: "{{ vpn_wg_client_public_keys | default({}) | combine({item.item.name: item.content | b64decode}) }}"
  loop: "{{ vpn_wg_client_public_keys_raw.results }}"
  no_log: true
