---
- name: Read client private keys
  ansible.builtin.slurp:
    src: "/etc/wireguard/keys/{{ item.name }}_priv"
  register: vpn_wg_client_private_keys_raw
  loop: "{{ vpn_wg_clients }}"
  no_log: true

- name: Map client private keys to dictionary
  ansible.builtin.set_fact:
    vpn_wg_client_private_keys: "{{ vpn_wg_client_private_keys | default({}) | combine({item.item.name: item.content | b64decode}) }}"
  loop: "{{ vpn_wg_client_private_keys_raw.results }}"
  no_log: true

- name: Generate client .conf files
  ansible.builtin.template:
    src: clients.conf.j2
    dest: "/etc/wireguard/configs/{{ client.name }}.conf"
    owner: root
    group: root
    mode: "0600"
  loop: "{{ vpn_wg_clients }}"
  loop_control:
    loop_var: client
  no_log: true

- name: Generate QR codes for mobile clients
  ansible.builtin.command:
    cmd: "qrencode -t png -o /etc/wireguard/configs/{{ item.name }}.png -r /etc/wireguard/configs/{{ item.name }}.conf"
    creates: "/etc/wireguard/configs/{{ item.name }}.png"
  loop: "{{ vpn_wg_clients }}"
