services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop@sha256:64b2bf5cd98525669dee1e0d1f618b9c939eddee6331b8708c9223ea14dc443a
    container_name: Prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/prowlarr/config:/config
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
