services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop@sha256:337a64f9a1a2d452cd58a1354599313b9ecb82acf43ba2fa85dfaed0f0e9276a
    container_name: Prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/prowlarr/config:/config
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
