services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop@sha256:e7a05286500b6e51084b0ba263dbbaf825db1ec7b731bf18aea30df84714e5f6
    container_name: Prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/prowlarr/config:/config
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
