services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop@sha256:2b2db31bb446db2dd29ac0596bfd82847f5778c93620917604c07d7d654a921e
    container_name: Prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/prowlarr/config:/config
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
