services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest@sha256:65049b0e8af551bb14c5e447861ac856c9902a1cc13033d3a08f10aee142fa66
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/ombi/config:/config
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
