services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest@sha256:a6f76ac521ba01eee2e9f0c23a3fed22e56630d97a04d5eeaeaa36c1e681640d
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/ombi/config:/config
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
