services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest@sha256:22d6ebadbaaa728571353e74dc2173719e0fb02d4eaec551a7e9d2ee99ef68ac
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/ombi/config:/config
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
