services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest@sha256:1394d2346ea40f3dff319a8efdb978aa115bc69cda5ed46ae40bf36ef4600da3
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/ombi/config:/config
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
