---
services:
  bitwarden_backup:
    image: bruceforce/vaultwarden-backup:2.1.6
    container_name: BitWarden-backup
    network_mode: bridge
    restart: unless-stopped
    init: true
    volumes:
      - /dockerconfig/bitwarden/data:/data
      - /backuppool/Szerver/docker/backup/bitwarden:/backups
      - /dockerconfig/bitwarden/backup/logs:/logs
    environment:
      - BACKUP_DIR=/backups
      - LOG_DIR=/logs
      - CRON_TIME=0 5 * * *
      - DELETE_AFTER=5
      - TIMESTAMP=true
      - UID=1000 
      - GID=1000
      - BACKUP_ADD_DATABASE=true
      - BACKUP_ADD_ATTACHMENTS=true
      - BACKUP_ADD_CONFIG_JSON=true
      - BACKUP_ADD_ICON_CACHE=true
      - BACKUP_ADD_RSA_KEY=true
      - LOG_LEVEL=INFO
      - TZ=Europe/Budapest
