---

ups_nut_mode: "netserver"
ups_nut_ups_name: "mainups"
ups_nut_ups_desc: "UPS for the whole Rack"
ups_nut_ups_driver: "blazer_usb"
ups_nut_ups_port: "auto"
ups_nut_listen_ip: "0.0.0.0"
ups_nut_listen_port: "3493"
ups_notify_script: false
