---
- name: Install required packages
  ansible.builtin.package:
    update_cache: true
    state: present
    name: "{{ printer_print_packages }}"

- name: Install hplip from edge branch
  community.general.apk:
    update_cache: true
    state: present
    name:
      - hplip
    repository: http://dl-cdn.alpinelinux.org/alpine/edge/testing
  when: ansible_os_family == 'Alpine'
