---
- name: Ensure printer groups exists
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ printer_print_groups | default(['lp', 'scanner']) }}"

- name: Add my user to the groups
  ansible.builtin.user:
    name: "{{ my_user }}"
    groups: "{{ printer_print_groups }}"
    append: true
    state: present
