---
- name: Enable & Start cups/sane service
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - "{{ printer_cups_service_name }}"
    - "{{ printer_sane_service_name }}"
