---
services:
  jackett:
    image: ghcr.io/linuxserver/jackett:latest@sha256:8b332695cf822bef3ad6aef1f20f211756289aef95010c74ee2bf3a186a1ec5b
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/jackett/config:/config
      - /hdd/Movies:/downloads
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
