---
services:
  jackett:
    image: ghcr.io/linuxserver/jackett:latest@sha256:3a19570c780e4971140a4564a385e7a1d5b06a7a560a613f0f52785210fd583e
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/jackett/config:/config
      - /hdd/Movies:/downloads
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
