---
services:
  jackett:
    image: ghcr.io/linuxserver/jackett:latest@sha256:fe3facd48302190c2e4144f0c0ea752e775ba0147813629255608a6a899c3a43
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/jackett/config:/config
      - /hdd/Movies:/downloads
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
