---
services:
  jackett:
    image: ghcr.io/linuxserver/jackett:latest@sha256:cf98e630224a3d8788926fd31e8a97c6c1a6f138b15cd7a3c795867d0fc954d4
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/jackett/config:/config
      - /hdd/Movies:/downloads
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
