---
services:
  jackett:
    image: ghcr.io/linuxserver/jackett:latest@sha256:140349b2f39ae9894801922786265119770b19061e8a9285d7dcc1f1451ed639
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/jackett/config:/config
      - /hdd/Movies:/downloads
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
