---
services:
  jackett:
    image: ghcr.io/linuxserver/jackett:latest@sha256:184a2944a14d6e42e0cbe7068e1b5f8fe215c38dfb0901e7bace371c699caa1a
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /dockerconfig/jackett/config:/config
      - /hdd/Movies:/downloads
    restart: unless-stopped
networks:
  default:
    name: nginx_default
    external: true
