import os
from time import sleep
import urllib.request
import subprocess
import hashlib
from pathlib import Path as pathlibpath
from jinja2 import Template
import smtplib
from email.message import EmailMessage
import markdown

DRIFTED_FILES = {
    "drifted": [],
    "missing_from_host": [],
    "new_on_host": [],
}

# The Report template is generated by AI
REPORT_TEMPLATE = """
# 🛡️ Drift Analysis Report

**Node:** {{ node }} | **VM:** {{ vm_name }}
**Source of Truth (Repo):** `{{ repo }}`
**Config Directory:** `{{ config_dir }}`

---

## 📊 Summary

| Category | Count | Status |
| :--- | :---: | :--- |
| ⚠️ **Drifted Files** (Content mismatch) | **{{ drifted|length }}** | {% if drifted %}⚠️ Drift Detected{% else %}✅ OK{% endif %} |
| ❌ **Missing from Host** (Repo only) | **{{ missing_from_host|length }}** | {% if missing_from_host %}❌ Missing{% else %}✅ OK{% endif %} |
| 🆕 **New on Host** (Untracked) | **{{ new_on_host|length }}** | {% if new_on_host %}ℹ️ Untracked{% else %}✅ OK{% endif %} |

---

## ⚠️ 1. Drifted Files (Content Mismatch)
*Files present on the host whose SHA-256 hashes differ from the Git repository:*

{% if drifted %}
{% for file in drifted %}
- 📄 `{{ file }}`
{% endfor %}
{% else %}
✨ *No drift detected! All tracked files match the repository.*
{% endif %}

---

## ❌ 2. Missing from Host
*Files defined in the Git repository that do NOT exist on the host system:*

{% if missing_from_host %}
{% for file in missing_from_host %}
- 🚫 `{{ file }}`
{% endfor %}
{% else %}
✨ *All repository files are present on the host!*
{% endif %}

---

## 🆕 3. New Configs on Host
*Configurations or directories found on the host that are NOT tracked in the Git repository:*

{% if new_on_host %}
{% for file in new_on_host %}
- ➕ `{{ file }}`
{% endfor %}
{% else %}
✨ *No untracked or new files found on the host!*
{% endif %}

---
*Report generated automatically for {{ node }} / {{ vm_name }}*
"""

def check_envs(environment_vars):
    for vars in environment_vars:
        if not os.environ.get(vars):
            print(f"Error: {vars} not set!")
            return False
    print("Every variable are set... Continue")
    return True

def check_pathes():
    conf_dir = os.getenv('CONFIGDIR', None)
    repo = os.getenv('REPO')
    if not conf_dir:
        return False
    
    if os.path.exists(conf_dir):
        print(f"Found {conf_dir} in the system")

    url = f"https://github.com/{repo}"
    with urllib.request.urlopen(url) as response:
        print(response.status)
        if response.status == 200:
            if not os.path.exists(f'/app/{repo.split("/")[1]}'):
                print("Github repo found! Cloning...")
                try:
                    subprocess.run(["git", "clone", url], check=True)
                    return True
                except Exception as e:
                    print(f"Error while cloning {url}: {e}")
                    return False
            else:
                print("Github repo already cloned! Pulling changes...")
                if pull_changes(repo=repo):
                    return True
        return False

def pull_changes(repo):
    os.chdir(f"/app/{repo.split('/')[1]}")
    try:
        subprocess.run(["git", "pull"],check=True)
        return True
    except Exception as e:
        print(f"Error while pulling changes from {repo}: {e}")

def check_diffs():
    repo = os.environ.get("REPO").split("/")[1]
    vm = os.environ.get("VM_NAME")
    node = os.environ.get("NODE")
    config_dir = os.environ.get("CONFIGDIR")
    if not os.path.exists(f"/app/{repo}/{node}/{vm}/Configs/"):
        return False
    if repo and vm and node:
        check_for_drifts(repo=repo, node=node, vm=vm, config_dir=config_dir)
        host_dirs = f"{config_dir}"
        repo_dirs = f"/app/{repo}/{node}/{vm}/Configs/"
        check_for_news(host_dir=host_dirs, repo_dir=repo_dirs)
        generate_report()
        if not os.environ.get("DRY_RUN", True):
            print("Automatic fix is disabled, exiting...")
            return

def check_for_news(host_dir, repo_dir):
    global DRIFTED_FILES
    if os.path.exists(host_dir) and os.path.exists(repo_dir):
        for host_config_dirs in os.listdir(host_dir):
            if host_config_dirs not in os.listdir(repo_dir):
                print(f"Found NEW configs in {host_config_dirs}, adding it to the report!")
                DRIFTED_FILES["new_on_host"].append(f"{pathlibpath(host_dir).joinpath(host_config_dirs)}")
    return

def check_for_drifts(repo, node, vm, config_dir):
    global DRIFTED_FILES
    for services in os.listdir(path=f"/app/{repo}/{node}/{vm}/Configs/"):
        base_dir = pathlibpath(f"/app/{repo}/{node}/{vm}/Configs/")
        target_dir = base_dir.joinpath(services)
        to_find = ["docker-compose.*", ".env.enc", "*.template"]
        for found in to_find:
            for target_files in target_dir.rglob(found):
                rel_path = target_files.relative_to(base_dir)
                host_path = f"{config_dir}/{rel_path}"
                if os.path.exists(host_path):
                    if not check_file_hash_diff(repo_file_path=target_files, host_file_path=host_path):
                        print(f"Drift found in {target_files} - {host_path}, adding it to the report!")
                        DRIFTED_FILES["drifted"].append(f"{host_path}")
                else:
                    print(f"File not found on the host system: {target_files}, adding it to the report!")
                    DRIFTED_FILES["missing_from_host"].append(f"{target_files}")
        return True


def check_file_hash_diff(repo_file_path, host_file_path):
    repo_files_hash = get_sha265(target_file=repo_file_path)
    host_files_hash = get_sha265(host_file_path)

    if host_files_hash == repo_files_hash:
        print("No difference found")
        return True
    else:
        print("Drift found")
        return False

def get_sha265(target_file):
    with open(target_file, "rb") as f:
        digest = hashlib.file_digest(f, "sha256")
        print(digest.hexdigest())
        return digest.hexdigest()

def generate_report():
    global DRIFTED_FILES
    template = Template(REPORT_TEMPLATE)

    report_output = template.render(
        node=os.environ.get("NODE", "N/A"),
        vm_name=os.environ.get("VM_NAME", "N/A"),
        repo=os.environ.get("REPO", "N/A"),
        config_dir=os.environ.get("CONFIGDIR", "N/A"),
        drifted=DRIFTED_FILES["drifted"],
        missing_from_host=DRIFTED_FILES["missing_from_host"],
        new_on_host=DRIFTED_FILES["new_on_host"],
    )
    print(report_output)

    with open("/app/drift_report.md", "w", encoding="utf-8") as f:
        f.write(report_output)
    generate_email(markdown_report=report_output)

def generate_email(markdown_report):
    html_content = markdown.markdown(markdown_report, extensions=['tables'])

    styled_html = f"""
    <html>
    <head>
    <style>
        body {{ font-family: Arial, sans-serif; color: #333; line-height: 1.6; }}
        table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #f2f2f2; }}
        code {{ background-color: #f4f4f4; padding: 2px 4px; border-radius: 4px; }}
    </style>
    </head>
    <body>
        {html_content}
    </body>
    </html>
    """

    envs = ["EMAIL_TO", "EMAIL_FROM", "SMTP_SERVER", "SMTP_PORT", "SMTP_USER", "SMTP_PASSWORD"]
    if check_envs(envs):
        msg = EmailMessage()
        msg['Subject'] = f"🛡️ Drift Report - {os.getenv('NODE')} / {os.getenv('VM_NAME')}"
        msg['From'] = f"{os.getenv('EMAIL_FROM')}"
        msg['To'] = f"{os.getenv('EMAIL_TO')}"
        msg.set_content(markdown_report)
        msg.add_alternative(styled_html, subtype='html')
        send_email(msg=msg)

def send_email(msg):
    try:
        with smtplib.SMTP(f"{os.getenv('SMTP_SERVER')}", f"{os.getenv('SMTP_PORT')}") as server:
            server.starttls()
            server.login(f"{os.getenv('SMTP_USER')}", f"{os.getenv('SMTP_PASSWORD')}")
            server.send_message(msg)
        print("E-Mail sent!")
    except Exception as e:
        print(f"Error while trying to send E-Mail: {e}")

def main():
    environment_vars = ["CONFIGDIR", "REPO", "VM_NAME", "NODE", "DRY_RUN"]
    if check_envs(environment_vars=environment_vars) and check_pathes():
        check_diffs()
    else:
        exit(0)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("Script interrupted by user. Exiting.")
        exit(0)


