FROM python:3.14.7-alpine
RUN apk add --no-cache su-exec git tini docker-cli docker-cli-compose tzdata
RUN pip install --no-cache-dir jinja2 markdown

ENV PYTHONUNBUFFERED=1
COPY entrypoint.sh /entrypoint.sh

RUN mkdir /app
ADD app.py /app
WORKDIR /app
RUN mkdir /app/trash

RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/sbin/tini", "--", "/entrypoint.sh"]

CMD [ "tail", "-n", "0", "-f", "/var/log/cron.log" ]
