name: Check files on PR
on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read
  contents: read

jobs:
  detect-changes:
    runs-on: self-hosted
    name: "Detect Changed Files"
    outputs:
      files: ${{ steps.changed-files.outputs.all_changed_files }}
      yaml: ${{ steps.changed-files.outputs.yaml_all_changed_files}}
      has_changes: ${{ steps.changed-files.outputs.any_changed }}
      yaml_has_changes: ${{ steps.changed-files.outputs.yaml_any_changed }}
      ansible_has_changes: ${{ steps.changed-files.outputs.ansible_any_changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - name: Get changed Files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          dir_names_max_depth: 5
          files_yaml: |
            yaml:
              - '**.yaml'
              - '**.yml'
            ansible:
              - 'ansible/**'

  check-yaml:
    runs-on: self-hosted
    name: "YAML Syntax Check"
    needs: detect-changes
    if: needs.detect-changes.outputs.yaml_has_changes == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Lint YAML files & Validate Compose File
        env:
          CHANGED_FILES: ${{ needs.detect-changes.outputs.yaml }}
        run: |
          for file in ${CHANGED_FILES}; do
            echo "Linting file: $file"
            python3 -m yamllint -d "{extends: relaxed, rules: {line-length: disable, document-start: disable, new-lines: disable}}" "$file"

            filename=$(basename "$file")
            if [[ '$filename' == 'docker-compose.yml' || '$filename' == 'docker-compose.yaml' ]]; then
              echo "Checking Compose file: $file"
              dir=$(dirname "$file")
              touch "$dir/.env.ci"

              grep -oE '\$\{?[A-Za-z0-9_]+' "$file" | tr -d '${' | sort -u | while read -r var; do
                echo "${var}=REDACTED" >> "$dir/.env.ci"
              done

              docker compose --env-file "$dir/.env.ci" -f "$file" config -q
              response=$?

              rm -f "$dir/.env.ci"

              if [ '$response' -ne 0 ]; then
                echo "$file is not a valid compose file"
                exit $response
              fi
            fi
          done

  check-ansible:
    runs-on: self-hosted
    name: "Ansible playbook lint"
    needs: detect-changes
    if: needs.detect-changes.outputs.ansible_has_changes == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Vault password
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ansible/.vault_pass

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          setup_python: "true"
          working_directory: "ansible"
          requirements_file: requirements.yml

      - name: Clean Up
        if: always()
        run: |
          rm -f ansible/.vault_pass

  gitleaks-scan:
    name: "Gitleaks Secret Scan"
    runs-on: self-hosted
    if: ${{ always() }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOME: /app/github-runner

  check-response:
    name: "Check Response"
    runs-on: self-hosted
    if: ${{ always() }}
    needs: [detect-changes, check-yaml, check-ansible, gitleaks-scan]
    steps:
      - name: Verify Checks Results
        run: |
          YAML_RES="${{ needs.check-yaml.result }}"
          ANSIBLE_RES="${{ needs.check-ansible.result }}"
          GITLEAKS_RES="${{ needs.gitleaks-scan.result }}"

          echo "YAML Check result: $YAML_RES"
          echo "Ansible Check result: $ANSIBLE_RES"
          echo "Gitleaks result: $GITLEAKS_RES"

          if [[ "$YAML_RES" == "failure" || "$YAML_RES" == "cancelled" || \
                "$ANSIBLE_RES" == "failure" || "$ANSIBLE_RES" == "cancelled" || \
                "$GITLEAKS_RES" == "failure" || "$GITLEAKS_RES" == "cancelled" ]]; then
            echo "Check failed!"
            exit 1
          fi
          echo "Everything looks good!"
