name: Update Docker Containers
on:
  push:
    branches:
      - main
    paths:
      - 'PVE/Docker/Configs/**'
      - 'PVE/Media/Configs/**'
      - 'PVE/Docs_Monitoring/Configs/**'
      - 'PVE/CI_Worker/Configs/**'
jobs:
  deploy-services:
    name: "Deploy Docker Compose Services"
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install SOPS
        uses: nhedger/setup-sops@v3
        with:
          version: "3.13.3"

      - name: Install Ansible & Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user ansible
          echo "$(ansible --version)"
          ansible-galaxy collection install ansible.posix
          ansible-galaxy collection install community.general

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Vault password
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ansible/.vault_pass

      - name: Create config files from templates
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: |
          find "./" -type f -name "*.template" -not -path "*/extensions/*" -not -path "*/code-server/*" 2> /dev/null | while read -r template; do
            basedir=$(dirname "$template")
            if [ -f "$basedir/.env.enc" ]; then
              sops --input-type dotenv --output-type dotenv --decrypt "$basedir/.env.enc" > "$basedir/.env"
            fi

            if [ -f "$basedir/.env" ]; then
              echo "Loading environment variables from .env..."
              set -a
              source "$basedir/.env"
              set +a
            fi

            output_file="${template%.template}"
            echo "Processing: $template -> $output_file"
            envsubst < "$template" > "$output_file"

            if [ -f "$basedir/.env" ]; then
              rm "$basedir/.env"
            fi
          done

      - name: Deploy stacks
        working-directory: ansible
        env:
          ANSIBLE_SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_CONFIG: 'ansible.cfg'
        run: |
            ansible-playbook site.yml --limit docker_hosts --tags docker_host
