name: "Run ansible playbook"
on:
  push:
    branches:
      - main
    paths:
      - 'ansible/**'

  workflow_dispatch:
    inputs:
      args:
        description: 'Args for ansible playbook(e.g.: --limit docker-hosts --check )'
        required: false
        default: ''

jobs:
  run-ansible-playbook:
    name: Run Ansible Playbook
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install Ansible & Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user ansible
          echo "$(ansible --version)"
          ansible-galaxy collection install ansible.posix
          ansible-galaxy collection install community.general

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Vault password
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ansible/.vault_pass

      - name: Run site.yml playbook
        working-directory: ansible
        env:
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_CONFIG: 'ansible.cfg'
        run: |
          ARGS="${{ inputs.args }}"
          if [ -n "$ARGS" ]; then
            ansible-playbook site.yml $ARGS
          else
            ansible-playbook site.yml --check
          fi

      - name: Clean Up
        if: always()
        run: |
          rm -f ansible/.vault_pass
